engines:
  markdownlint:
    enabled: true
    checks:
      # first headers should be top-level
      MD002:
        enabled: false
      # line length
      MD013:
        enabled: false
      # blank lines around headers
      MD022:
        enabled: false
      # surround lists with blank lines
      MD032:
        enabled: false
      # inline HTML
      MD033:
        enabled: false
  sass-lint:
    enabled: true
    checks:
      clean-import-paths:
        enabled: false
      empty-line-between-blocks:
        enabled: false
      final-newline:
        enabled: false
      force-element-nesting:
        enabled: false
      force-pseudo-nesting:
        enabled: false
      nesting-depth:
        enabled: false
      no-important:
        enabled: false
      no-misspelled-properties:
        enabled: false
      no-qualifying-elements:
        enabled: false
      quotes:
        enabled: false
      single-line-per-selector:
        enabled: false
      url-quotes:
        enabled: false