# do not use tabs in config files!
# recommended command when testing: bundle exec jekyll serve --livereload --drafts --watch

# production only
# recommended command jekyll build
destination: ../pro
url: https://absurdrealms.com

# jekyll config
timezone: America/Toronto
title: Absurd Realms
permalink: /:categories/:title/
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
theme: jekyll-theme-schizoid

# jekyll-theme-schizoid config
theme-schizoid:
  hideFooter: false
  hideFooterCredit: true

# default front matter
defaults:
  -
    values:
      style: style.css
      showSiteTitle: true
      showPageTitle: true
      display_last_modified_at: true
  -
    scope:
      type: pages
    values:
      layout: page
  -
    scope:
      type: posts
    values:
      layout: post
      category: news

# extras      
kramdown:
  parse_block_html: true
  footnote_backlink: ↑
sass:
  style: compressed
  sourcemap: never
pagination:
  enabled: true
  per_page: 7
  permalink: /:num/
  title: :title
  sort_reverse: true
feed:
  excerpt_only: true
  posts_limit: 7

# also add the plugins in the Gemfile if they have a gem
# use gem uninstall to remove unwanted gems
# run bundle install if adding uninstalled gems
# to update the Gemfile.lock file, use the command: bundle update