# do not use tabs in config files!
# recommended command when testing: bundle exec jekyll serve --port 4002 --livereload --livereload-port 35731 --drafts --watch --incremental
# recommended command if modifying data or some pages don't update properly: bundle exec jekyll serve --port 4002 --livereload --livereload-port 35731 --drafts --watch

# production only
# recommended command jekyll build
destination: _site
url: https://absurdrealms.com

# jekyll config
timezone: America/Toronto
title: Absurd Realms
permalink: /:categories/:title/
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - README.md

# default front matter
defaults:
  -
    scope:
      type: pages
    values:
      layout: default
  -
    scope:
      type: posts
    values:
      layout: post
      category: news
  -
    scope:
      path: compendium/creatures/*/
      type: pages
    values:
      permalink: /compendium/creatures/:basename/
      main: Compendium
      main-url: /compendium/
      return: Creatures
      return-url: /compendium/creatures/
  -
    scope:
      path: compendium/life/*/
      type: pages
    values:
      permalink: /compendium/life/:basename/
      main: Compendium
      main-url: /compendium/
      return: Life
      return-url: /compendium/life/
  -
    scope:
      path: compendium/locations/*/
      type: pages
    values:
      permalink: /compendium/locations/:basename/
      main: Compendium
      main-url: /compendium/
      return: Locations
      return-url: /compendium/locations/
  -
    scope:
      path: compendium/physics/*/
      type: pages
    values:
      permalink: /compendium/physics/:basename/
      main: Compendium
      main-url: /compendium/
      return: Physics
      return-url: /compendium/physics/

# extras      
kramdown:
  parse_block_html: true
  footnote_backlink: ↑
sass:
  style: compressed
  sourcemap: never
pagination:
  enabled: true
  per_page: 7
  permalink: /:num/
  title: :title
  sort_reverse: true
feed:
  excerpt_only: true
  posts_limit: 7

# jekyll-theme-schizoid
custom_icon: /assets/images/ar_icon_small.png

# also add the plugins in the Gemfile if they have a gem
# use gem uninstall to remove unwanted gems
# run bundle install if adding uninstalled gems
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-tidy