# do not use tabs in config files!
# recommended command when testing: bundle exec jekyll serve --livereload --drafts --watch --incremental
# recommended command if modifying data files or same pages don't update properly: bundle exec jekyll serve --livereload --drafts

# production only
# recommended command jekyll build
destination: _site
url: https://absurdrealms.com

# jekyll config
timezone: America/Toronto
title: Absurd Realms
permalink: /:categories/:title/
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - README.md

# default front matter
defaults:
  -
    scope:
      type: pages
    values:
      layout: default
      info: true
  -
    scope:
      type: posts
    values:
      layout: post
      info: true
      category: news

# extras      
kramdown:
  parse_block_html: true
  footnote_backlink: ↑
sass:
  style: compressed
  sourcemap: never
pagination:
  enabled: true
  per_page: 7
  permalink: /:num/
  title: :title
  sort_reverse: true
feed:
  excerpt_only: true
  posts_limit: 7

# jekyll-theme-schizoid
custom_icon: /assets/images/ar_icon_small.png

# also add the plugins in the Gemfile if they have a gem
# use gem uninstall to remove unwanted gems
# run bundle install if adding uninstalled gems
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-tidy
  - jekyll-last-modified-at